- src/components/kiosk/kiosk.js
- src/index.js
키오스크 조회, 추가 기능 추가
Resolves: #4, #5
Ref: #3
> Add: 키오스크 조회, 추가 기능

- src/components/kiosk/kiosk.js
키오스크 추가 폼 요청 삭제 -> button으로 요청
Ref: #5
> Refactor: 키오스크 추가 코드 변경

- package-lock.json
- package.json
- src/components/loading.js
- src/components/menu/menu.js
#13 메뉴관리 링크 접속시 곧바로 useEffect 함수 실행됨, axios 기능을 활용하여 비동기 방식으로 서버에 데이터 요청함으로써 로딩 부담을 줄임, 로딩화면을 구현하고자 loading component 만듬, data 세팅 완료시 로딩화면 기능 멈춤, 테이블에 메뉴 전체 세팅됨, 추가로 등록하기 버튼도 만듬(아직 기능구현 안됨)
Resolves : #13 
Ref: #11 , #12 
Related to:
> Add: #13 메뉴 리스트 전체 조회 기능 구현

- package-lock.json
- package.json
- src/components/kiosk/kiosk.js
> Refactor: 키오스크 추가 

- src/App.js
- src/components/menu/addMenu.js
- src/components/menu/main.js
- src/components/menu/menu.js
> Add: menu.js용 라우터 설정

- src/components/menu/addMenu.js
menu main의 라우터 navigation 수정중
Resolves: #16 #14
Ref: #12
> Add: #16 #14 카테고리드롭박스 및 메뉴등록 기능

- src/components/kiosk/kiosk.js
- src/components/menu/addMenu.js
> Add: 키오스크 전원 변경

- src/App.js
- src/components/menu/addMenu.js
- src/components/menu/categoryBtn.js
- src/components/menu/main.js
- src/components/menu/menu.js
#15 menu component 폴더 내에 main.js 에 드롭다운 버튼으로 카테고리별 메뉴 조회 기능 구현 완료, categoryBtn.js 파일형태로 기능분리 성공
Resolves: #15
Ref: #11 #12
> Add: #15 드롭다운 박스 카테고리별 메뉴 조회 기능 구현

- src/components/kiosk/kiosk.js
키오스크 전원 변경 기능 추가
Resolves: #8
Ref: #3
>  Add: 키오스크 전원 변경

- src/components/order/Order.js
- src/components/order/orderItem.js
주문 리스트 조회 기능 추가 ( 옵션x)
Ref: #31
> Add : 주문 리스트 조회

- src/App.js
- src/components/kiosk/kiosk.js
- src/components/order/orderItem.js
- src/index.js
주문 리스트 조회 옵션 추가
Resovles: #31
Ref: #30
> Add: 주문 리스트 조회

- src/components/order/Order.js
- src/components/order/orderItem.js
주문 완료 기능 추가
Resolves: #32
Ref: #30
> Add: 주문 완료 기능

- src/App.js
- src/components/menu/main.js
- src/components/menu/menu.js
- src/components/menu/updateMenu.js
> Add: #17  메뉴 수정 기능 추가

- src/components/kiosk/kiosk.js
- src/components/order/Order.js
- src/components/order/orderItem.js
- src/components/order/util.js
주문 상세 및 수정 삭제 기능 추가
Resolves: #33
Ref: #30
> Add: 주문 상세 및 수정기능

- src/components/menu/addMenu.js
- src/components/menu/updateMenu.js
> Add: #51 메뉴 수정 및 등록페이지 디자인

- package-lock.json
- package.json
- src/App.js
- src/NavBar.Style.js
- src/NavBar.js
- src/SideBar.js
- src/components/kiosk/kiosk.js
SideBar 추가, NavBar 추가 NavBar는 디자인만 추가
> Add: SideBar, NavBar

- src/App.js
- src/SideBar.js
> Add: kiosk 화면 링크 연결

- src/components/header/HeaderMenu.js
- src/components/orderList/CartRow.js
- src/container/Menu.js
> Add: 장바구니 옵션 조회 기능 추가

- src/components/user/User.js
> Add: #62 Modal을 활용한 등록 기능

- src/SideBar.js
- src/components/user/User.js
- src/components/user/addUserModal.js
- src/components/user/updateUserModal.js
추가 모달 생성예정
Resolves: #63
Ref: #60
> Add: #63 modal을 활용한 수정, 삭제 완료

- src/components/user/User.js
- src/components/user/addUserModal.js
- src/components/user/deleteModal.js
- src/components/user/updateUserModal.js
> Add: #64  user 삭제 모달 추가

- src/components/user/User.js
- src/components/user/Util.js
> Add: #61  리스트 조회 기능

- src/components/user/User.js
- src/components/user/Util.js
- src/components/user/addUserModal.js
- src/components/user/deleteModal.js
- src/components/user/updateUserModal.js
> Add: #61 리스트 조회 UI 추가

- src/SideBar.js
- src/components/login/login.js
로그인 안 되어 있으면 sidebar 메뉴 표시 안하게 함 
Resolves : #96
Ref : #68
> Add : sidebar 표시

- src/components/order/Order.js
- src/components/order/util.js
> Add: 주문관리 옵션에 '없음' 표시 제거

- src/SideBar.js
- src/components/login/OwnerManage.js
주소창 입력으로 접근시도 막기 
Resolves:#70
Ref:#69
> Modify: owenrComponent 수정

- package-lock.json
- package.json
- src/components/menu/categoryBtn.js
- src/components/order/Order.js
#102 flower_kiosk 의 cart.js 와 현 프로젝트의 order.js 와 웹소켓 연결 성공 및 주문 정보 인식되면 refresh 기능이 동작되어 화면에선 실시간 최신화처럼 구현됨, 버벅거리는 증상도 없음
Resolves: #102
Ref: #94
> Add: #102 웹소켓 기능 주문관리 페이지에 적용 성공

- package.json
- src/SideBar.js
- src/components/order/Order.js
컴퓨터 재부팅 과정에서 파일에서 원인 모를 손상이 생겨 오류 수정 후 push 함
> 작업물 보호를 위해 임시 커밋(주석만 씀)

- package.json
- src/App.js
- src/SideBar.js
- src/components/Home.js
- src/components/kiosk/AddModal.js
- src/pages/kiosk.js
> Refactor: 키오스크 추가 모달 분리

- src/components/kiosk/UpdateModal.js
- src/pages/kiosk.js
> Refactor: 키오스크 수정 모달 분리

- src/components/menu/historymain/categoryBtn2.js
- src/components/menu/historymain/main2.js
- src/components/user/updateUserModal.js
> Add #109 메뉴 조회 페이지네이션 추가

- src/NavBar.js
네비바 아이디 옆에 권한 (rankText) 추가함
Resolves : #112
Ref : #68
> Add : 아이디 옆 rankText 추가

- src/NavBar.js
네비바 권한 영어를 한국어로 표시
Resolves : #112 
Ref : #68
> Modify : 네비바 권한 표시

- src/components/menu/main.js
> Add: #118 메뉴 조회 가격 정렬 기능 추가

- src/NavBar.js
- src/components/login/OwnerManage.js
슈퍼 전용 페이지 수정
Resolves:#95
Ref:#68
> Add:슈퍼계정 페이지 추가

- src/components/user/User.js
사용자 관리 페이지 처리 추가
Resolves: #121
Ref: #59
> Add: 사용자 관리 페이지 처리 추가

- src/components/menu/main.js
> Modify: #118 메뉴 리스트 조회 및 관리 기능수정

- package-lock.json
- package.json
- src/components/dashBoard/ExcelButton.js
- src/components/dashBoard/Header.js
- src/components/dashBoard/LineChart.js
- src/pages/DashBoard.js
> Add: 매출 엑셀 다운로드 기능

- src/index.js
토큰 만료시 로그아웃 처리
Resolves:#129
Ref:#68
> Add:토큰 만료시 로그아웃 처리

- package-lock.json
- package.json
- src/NavBar.js
- src/components/login/login.js
- src/index.js
쿠키를 이용한 아이디 저장 기능
Resolves:#133
Ref:#68
> Add: cookie를 이용한 아이디 저장기능

- package.json
- src/App.js
- src/SideBar.js
- src/components/order/Order.js
#102 flower_kiosk 의 Cart.js 에서 보낸 웹소켓 정보를 즉각적으로 응답받는 데 성공했음, 다만 코드 전체를 리팩토리 해야하는 상황이 오니 주석으로 '리팩토리 필요하다' 표기만 했음,  json 정보를 가지고 웹소켓 주고받을 수 있도록 기반 깔아둔 상황, 아직은 refresh 함수로 axios 를 이용하여 api 요청하는 방식은 변함없음
Resolves: #102 
Ref: #94
> Modify: #102 order.js 웹소켓 응답방식 수정

- package-lock.json
- package.json
- src/components/login/login.js
Mo# <타입> : <제목> 형식으로 작성하며 제목은 최대 50글자 정도로만 입력
> Add : cress-env 인스톨 추가

- package.json
- src/components/Home.js
- src/components/login/login.js
- src/index.js
로그인 상태에 따른 화면 수정
Resolves:#92
Ref:#68
> Modify: home.js 리팩토링

- src/index.js
index.js 로그아웃 함수로 처리했음
Resolves:#129
Ref:#68
> Modify: index.js 로그아웃 처리 함수

- src/components/user/User.js
> Modify : 사용자 관리 버튼 수정

- src/components/dashBoard/CircleChart.js
- src/components/dashBoard/DashTable.js
- src/components/dashBoard/Header.js
- src/index.js
- src/pages/DashBoard.js
> Add: #154 DashTable 기능 추가

- src/components/order/DetailModal.js
- src/index.js
- src/pages/Order.js
- src/pages/kiosk.js
#169 이전 코드는 무한요청, 무분별한 웹소켓 객체 생성 등 문제가 많아 다시 코드짬, 손님측에서 전달한 신호를 즉각적으로 메시지 전달받는 데 성공함, 다만 아직 모달까지 구현은 못함, 구현 성공시 #102 Modify로 푸시할 예정
Resolves: #169 
Ref: #102 -> 모달까지 진행예정
> Add: #169 웹소켓으로 주문정보 접수신호 응답성공

- src/components/dashBoard/CircleChart.js
- src/components/dashBoard/DashTable.js
- src/components/menu/updateMenu.js
- src/components/toolbar/SideBar.js
- src/pages/DashBoard.js
> Add: #156 Circle chart 기능 추가

- package.json
- src/App.js
- src/index.js
- src/pages/Order.js
- src/pages/kiosk.js
#102 웹소켓 코드 개선완료, state 데이터 소실 문제로 임의로 만든 불필요한 websocket 객체 생성코드 모두 제거, index.js 에서 최초 객체 생성 후 필요한 1차로 app.js, 2차로 order.js 에 dispatch 함수를 활용하여 웹브라우저 새로고침시 정보누락 문제를 막는 데 성공, 무한요청 증상 또한 없고 이전 기능들 역시 문제없음
Resolves: #102 
Ref: #94
> Refactor: #102 웹소켓 기존코드 개선완료

- src/components/order/DetailModal.js
- src/components/order/style.js
주문 관리 페이지 모달 창 디자인 추가
Resloves: #183
Ref: #94
> Add: 주문 관리 페이지 모달 창 디자인

- src/components/dashBoard/DashTable.js
대쉬 테이블 옵션네임 추가함
Resolves : #154
Ref : #117
> Modify : 대쉬 테이블 수정

- src/App.js
- src/index.js
- src/pages/Home.js
- src/pages/Order.js
- src/pages/kiosk.js
#102 코드를 order.js 처리하는 코드를 제거하고 app.js로 전달 받도록 수정, 손님측에서 보내는 모든 메시지를 app.js 에서 동시에 전달 받도록 코드 구현, order.js 는 기존 코드 모두 제거 후 props 를 통해 boolean 값을 인식시키고 변화를 감지하면 자동 refresh 처리하도록 만듬
> Refactor: #102 주문정보 메시지 신호 응답코드 리팩토링

- src/components/dashBoard/ExcelButton.js
csv 엑셀 차트 옵션 수정
Resolves : #127
Ref : #117
> Modify : csv 수정

- src/App.js
- src/components/order/style.js
- src/index.js
#103 bootstarp 양식으로 toast 기능을 통해 주문이 들어올 때마다 어느 페이지에서든 UI 상에서 보이도록 띄우기 성공, app.js 에 코드를 작성함
Resolves: #103 
Ref: #94 
Related: #140 , #141 원인 모를 에러 타이밍이 존재하나 원인을 아직 찾지 못함, 그로인해 웹소켓 재요청 과정에서 자동연결 실패, 실패원인은 끊겼음에도 클라이언트와 서버가 서로 연결된 줄 알고 오해중, 웹브라우저 새로고침을 하지 않는 이상 로그아웃처리하더라도 그대로임
> Add: #103 주문알림 띄우기 성공

- src/components/dashBoard/CircleChart.js
- src/components/dashBoard/DashTable.js
- src/components/dashBoard/LineChart.js
- src/pages/DashBoard.js
로딩이미지는 추가예정
Resolves: #198 
Ref: #117
> Add: #117대쉬보드 조건변경으로 지연시 로딩처리 추가

- src/components/menu/updateMenu.js
> Modify: menu update 오류 해결

- src/components/dashBoard/CircleChart.js
- src/components/dashBoard/LineChart.js
차트 마우스 오버 가격 표시 수정
Resolves : #155 #156
Ref : #117
> Modify : 차트 가격 원 표시

- src/pages/Order.js
주문 없을 때 보여지는 페이지
Resolves: #210
Ref: #94
> Add: 주문 empty view

- src/components/menu/addMenu.js
메뉴 추가 시 카테고리, 이름, 가격, 요약, 상세 입력해야만 등록 되도록 수정 , 가격은 숫자만 입력 되도록, 이미지는 안건듬 
Resolves : #217
Ref : #11
> Modify : 메뉴 추가 유효성 검사

- src/components/menu/updateMenu.js
수정폼 유효성 추가함 이름, 요약, 상세, 가격
Resolves : #217
Ref : #11
> Modify : 수정폼 유효성 추가함

- src/App.js
- src/components/toast/OrderToast.js
- src/components/toolbar/NavBar.js
- src/index.js
- src/pages/DashBoard.js
- src/pages/Order.js
- src/pages/kiosk.js
- src/pages/login.js
- src/util/websocket.js
> Refator: 주문관리 웹소켓

- src/components/menu/addMenu.js
- src/components/menu/updateMenu.js
정규 표현식 추가
Resolves : #217
Ref : #11
> Modify : 유효성 수정

- package.json
- src/components/menu/main.js
- src/components/menu/updateMenu.js
- src/components/order/orderItem.js
- src/index.js
- src/pages/Order.js
menuId session storage를 활용해서 500에러 막음
> Modify: order.js isEmpty가 true일시 이미지 나오게

- src/components/user/addUserModal.js
- src/pages/User.js
직원 추가 유효성 검사 , 아이디 중복 검사
Resolves : #232
Ref : #59
> Add : 직원 추가 유효성 추가

- package.json
- src/components/login/AddModal.js
- src/components/login/DelModal.js
- src/components/login/UpdateModal.js
- src/components/toolbar/SideBar.js
- src/pages/OwnerManage.js
사장님 수정 모달 수정했습니다.
Resolves:#235
Ref:#68
> Modify: 사장님 수정 유효성 수정

- package.json
- src/pages/kiosk.js
- src/util/websocket.js
#137 이전에는 id 구별없이 동작되는 바람에 키오스크 전체에 영향이 있었다면 이번에는 개별로 구분 후 동작되도록 만들었음
Resolves: #137 
Ref: #94 
Related to: #138 (웹브라우저 정책에 때문에 구현은 되었지만 지속적으로 유지가 안됨, 그에 대한 대처 로직 아직 없음)
> Fix: #137 키오스크 제어장치 id 별 구분 후 행동조치 되도록 만듬

- src/components/user/addUserModal.js
error state 삭제
Resolves:#242
Ref:#60
> Modify: error state 삭제

- src/pages/login.js
Login.js  입력폼 입력시 콘솔에러 수정 
Resolves:#246
Ref:#68
> Add: login 페이지 console 에러 수정

- package.json
- src/components/menu/addMenu.js
- src/components/menu/updateMenu.js
- src/util/websocket.js
메뉴등록 유효성 검사 완료 및 디자인 변경(이미지 제거 )
Resolves: #217
Ref: #11
> Modify: 메뉴 등록  유효성 검사 완료 및  디자인 변경

- package.json
- src/components/kiosk/AddModal.js
- src/pages/kiosk.js
- src/util/websocket.js
#5 키오스크 정보를 추가시 유효성 검사 확인 후 등록되도록 구현함
> Add: #5 키오스크 정보 추가시 유효성 검사 기능 추가

- src/components/menu/addMenu.js
- src/pages/Order.js
- src/pages/login.js
login.js  state 에서 setCid 사용하지 않아 삭제했습니다,
Resolves:#258
Ref:#257
> Add: login.js setCid 삭제
